[package]
name = "nix-libstore"
version.workspace = true
edition.workspace = true
description = "Core Nix datastructures"

[dependencies]
anyhow = "1.0"
nix-base32 = "0.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
